name: doc

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - uses: astral-sh/setup-uv@v10.0.1
        with:
          uv-version: "0.11.16"
          enable-cache: true

      - run: uv sync --locked --python 3.13 --extra doc --extra stim

      - name: Make docs
        run: uv run --no-sync sphinx-build -W docs/source docs/build

      - name: Save docs
        uses: actions/upload-artifact@v7
        with:
          name: html-docs
          path: docs/build

  lint-text:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v10.0.1
        with:
          uv-version: "0.11.16"
          enable-cache: true

      - run: uv sync --locked --python 3.12 --extra dev

      - name: Run language-agnostic linters
        run: uv run --no-sync pre-commit run --all-files
